//used to throw an error
try {
  alert("Hellow!");
} catch (err) {
  console.log(err);
}
